#-------------------------------
# General Site Settings
title: Blog
logo: /images/icon.png
description: blog lists intrests and updates .
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Pal Agrawal
  bio:  Blogger, Developer and Entrepreneur
  avatar: '/images/avatar.png'
  show_author: true
  share_enabled: true

social:
- {icon: "ion-logo-github", label: Github, link: "https://github.com/pal404error"}
- {icon: "ion-logo-linkedin", label: LinkedIn, link: "https://www.linkedin.com/in/pal404error/"}
- {icon: "ion-logo-twitter", label: Twitter, link: "https://twitter.com/pal404error"}
- {icon: "ion-logo-dribbble", label: Medium, link: "https://pal404error.medium.com/"}

# Example of adding a new link to the author section and footer - {icon: "ion-logo-github", label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: Hey,
  hero__description: Read along, follow up !!
  hero__image: '/images/avatar.png'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
# mailchimp: true # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
# mailchimp__title: Get interesting news # Add your Title
# mailchimp__text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
# mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
# mailchimp__button__text: Join # Add your button text


#-------------------------------
# # Contact Settings
# contact:
#   email: palnft69@gmail.com # Add your email for contact form
#   description: # Add a description of your form



# #-------------------------------
# # Comment Section (Disqus)
# disqus-identifier: # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed